import Logo from "./components/Logo";
import Navigation from "./components/Navigation";
export const metadata = {
  title: "The Wild Oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-6">
        <div className="flex flex-col gap-6">
          <Logo/>
          <Navigation/>
          <main>{children}</main>
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
